#!/bin/bash
#***************************************************************
# brief:
#       get ffmpeg x264 lib's path
#***************************************************************

runUsage()
{
    echo -e "\033[31m *****************************************\033[0m"
    echo "     Usage:                                                 "
    echo "          $0  \$FFMPEGDir                                   "
    echo "                                                            "
    echo -e "\033[31m *****************************************\033[0m"
}

runInit()
{
    ConfigShell="${FFMPEGDir}/ffbuild/config.sh"
}

runParsex264LibPath()
{
    #config shell file was generated by  ffmpeg/configure
    #************************************************************
    #************************************************************

    #x264 lib path info may looks like:
    #************************************************************
    #extralibs_avcodec="-framework QuartzCore -framework AppKit -framework OpenGL -framework QuartzCore -framework AppKit -framework OpenGL -framework Foundation -framework AVFoundation -framework CoreVideo -framework CoreMedia -L/usr/local/lib -lSDL2 -framework QuartzCore -framework VideoDecodeAcceleration -framework CoreFoundation -framework QuartzCore -framework CoreFoundation -framework AudioToolbox -framework CoreMedia -framework CoreFoundation -framework VideoToolbox -framework CoreMedia -framework CoreVideo -L/usr/local/lib -lSDL2 -liconv -Wl,-framework,CoreFoundation -Wl,-framework,Security -L/usr/local/lib -lSDL2 -L/usr/local/Cellar/x264/r2748/lib -lx264 -framework CoreGraphics -lm -lbz2 -lz -pthread -pthread -framework CoreServices
    #************************************************************

    LibPathInfo=`cat ${ConfigShell} | egrep "x264" | head -1`

    LibPathInfo_02=`echo ${LibPathInfo} | awk 'BEGIN {FS="-lx264"} {print $1}'`
    LibPathInfo_03=`echo ${LibPathInfo_02} | awk '{print $NF}'`
    FFMPEGx264LibPath=`echo ${LibPathInfo_03} | awk 'BEGIN {FS="-L"} {print $NF}'`

    echo "FFMPEGx264LibPath is  $FFMPEGx264LibPath"

}

runCheck()
{
    if [ ! -d ${FFMPEGDir} ];then
        echo "FFMPE dir doest not exist, please double check"
        runUsage
        exit 1
    fi

    if [ ! -e "${ConfigShell}" ];then
        echo -e "\033[32m *****************************************\033[0m"
        echo " ${ConfigShell} configure shell for ffmpeg build not found!"
        echo " please run below command and generate configure shell script"
        echo "    cd ${FFMPEGDir} "
        echo "    ./configure \$ffmpegPreset"
        echo -e "\033[32m *****************************************\033[0m"
    fi
}

runMain()
{
    runInit

    runCheck

    runParsex264LibPath
}

#*************************************************************

if [ $# -lt 1 ]
then
    runUsage
    exit 1
fi


FFMPEGDir=$1
runMain

#*************************************************************





